//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Watermark.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "Watermark.h"


// Declare the bitmap loading function
extern void wxC6F36InitBitmapResources();

static bool bBitmapLoaded = false;


Watermark::Watermark(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC6F36InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* bsMain = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(bsMain);
    
    wxArrayString m_listBox5Arr;
    m_listBox5 = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), m_listBox5Arr, wxLB_SINGLE);
    
    bsMain->Add(m_listBox5, 0, wxALL, 5);
    
    m_gauge7 = new wxGauge(this, wxID_ANY, 100, wxDefaultPosition, wxSize(-1,-1), wxGA_HORIZONTAL);
    m_gauge7->SetValue(10);
    
    bsMain->Add(m_gauge7, 0, wxALL, 5);
    
    SetName(wxT("Watermark"));
    SetSize(500,300);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
}

Watermark::~Watermark()
{
}
