//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Watermark.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CLIONPROJECTS_WATERMARK_WATERMARK_BASE_CLASSES_H
#define CLIONPROJECTS_WATERMARK_WATERMARK_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/listbox.h>
#include <wx/gauge.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class Watermark : public wxFrame
{
protected:
    wxListBox* m_listBox5;
    wxGauge* m_gauge7;

protected:

public:
    wxListBox* GetListBox5() { return m_listBox5; }
    wxGauge* GetGauge7() { return m_gauge7; }
    Watermark(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Watermark"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~Watermark();
};

#endif
